[project]
name = "videos"
version = "0.1.0"
description = ""
authors = [
    {name = "PlayfulMathematician"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "anyio (==4.9.0)",
    "audioop-lts (==0.2.1)",
    "av (==13.1.0)",
    "beautifulsoup4 (==4.13.4)",
    "build (==1.2.2.post1)",
    "cachecontrol (==0.14.3)",
    "certifi (==2025.6.15)",
    "cffi (==1.17.1)",
    "charset-normalizer (==3.4.2)",
    "cleo (==2.1.0)",
    "click (==8.2.1)",
    "cloup (==3.0.7)",
    "crashtest (==0.4.1)",
    "cryptography (==45.0.5)",
    "decorator (==5.2.1)",
    "distlib (==0.3.9)",
    "dulwich (==0.22.8)",
    "fastjsonschema (==2.21.1)",
    "ffmpeg (==1.4)",
    "filelock (==3.18.0)",
    "findpython (==0.6.3)",
    "glcontext (==3.0.0)",
    "h11 (==0.16.0)",
    "httpcore (==1.0.9)",
    "httpx (==0.28.1)",
    "idna (==3.10)",
    "installer (==0.7.0)",
    "isosurfaces (==0.1.2)",
    "jaraco-classes (==3.4.0)",
    "jaraco-context (==6.0.1)",
    "jaraco-functools (==4.2.1)",
    "jeepney (==0.9.0)",
    "keyring (==25.6.0)",
    "manim (==0.19.0)",
    "manimpango (==0.6.0)",
    "mapbox-earcut (==1.0.3)",
    "markdown-it-py (==3.0.0)",
    "mdurl (==0.1.2)",
    "moderngl (==5.12.0)",
    "moderngl-window (==3.1.1)",
    "more-itertools (==10.7.0)",
    "msgpack (==1.1.1)",
    "networkx (==3.5)",
    "numpy (==2.3.1)",
    "packaging (==25.0)",
    "pbs-installer (==2025.7.2)",
    "pillow (==11.3.0)",
    "pkginfo (==1.12.1.2)",
    "platformdirs (==4.3.8)",
    "poetry (==2.1.3)",
    "poetry-core (==2.1.3)",
    "pycairo (==1.28.0)",
    "pycparser (==2.22)",
    "pydub (==0.25.1)",
    "pyglet (==2.1.6)",
    "pyglm (==2.8.2)",
    "pygments (==2.19.2)",
    "pyproject-hooks (==1.2.0)",
    "rapidfuzz (==3.13.0)",
    "requests (==2.32.4)",
    "requests-toolbelt (==1.0.0)",
    "rich (==14.0.0)",
    "scipy (==1.16.0)",
    "screeninfo (==0.8.1)",
    "secretstorage (==3.3.3)",
    "shellingham (==1.5.4)",
    "skia-pathops (==0.8.0.post2)",
    "sniffio (==1.3.1)",
    "soupsieve (==2.7)",
    "srt (==3.5.3)",
    "svgelements (==1.9.6)",
    "tomlkit (==0.13.3)",
    "tqdm (==4.67.1)",
    "trove-classifiers (==2025.5.9.12)",
    "typing-extensions (==4.14.0)",
    "urllib3 (==2.5.0)",
    "virtualenv (==20.31.2)",
    "watchdog (==6.0.0)",
    "zstandard (==0.23.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
